---
- clean: ['~']

- shell:
    -
        - 'git submodule update --init --recursive --remote'
        - 'Updating submodules'

- link:
    ~/.ctags: ctags/ctags

    ~/.functions: zsh/functions

    ~/.gemrc: ruby/gemrc

    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore

    ~/.shell_aliases: zsh/shell_aliases

    ~/.tmux.conf: tmux/tmux.conf

    ~/.zlogin: zprezto/runcoms/zlogin
    ~/.zlogout: zprezto/runcoms/zlogout
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprezto: zprezto/
    ~/.zprofile: zsh/zprofile
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc

    zprezto/modules/prompt/functions/prompt_santiaro_setup: zsh/themes/prompt_santiaro_setup

    ~/.vim: vim/vim/
    ~/.vimrc: vim/vimrc

- shell:
    -
        - 'mkdir -p ~/.vim/backup ~/.vim/swap ~/.vim/undo'
        - 'Creating backup directories for Vim'
    -
        - 'vim +PluginClean +PluginInstall +qall'
        - 'Installing Vim Vundle managed plugins'
